# Generated by Django 3.2.3 on 2021-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opus_title', models.CharField(max_length=200)),
                ('opus_description', models.TextField()),
            ],
        ),
    ]
