# Generated by Django 3.2.3 on 2021-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_opuses_opus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opus',
            options={'verbose_name_plural': 'Opuses'},
        ),
        migrations.AddField(
            model_name='opus',
            name='opus_image',
            field=models.ImageField(null=True, upload_to='opus_image'),
        ),
    ]
